### PR TITLE
Fix: pass name as a property instead props.name

### PR DESCRIPTION
**Pull request by snettah**

### CODE REVIEW

**Comment by snettah** [comment]
#9

**Comment by pomber** [comment]
Thanks @snettah! nice catch.
Can you change it to `function App(props)` ? So we make it more explicit that `name` comes from `props`

**Comment by pomber** [comment]
Thanks a lot!

**Comment by snettah** [comment]
sorry i've forgot to update the commit message when i've force pushed, it's cool if you can do that !

**Pull request merged**
